<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Chart Library
    |--------------------------------------------------------------------------
    |
    | The default chart library to use when creating new charts.
    | Supported: "chartjs", "highcharts", "fusioncharts", "morris", "pie".
    |
    */

    'library' => 'chartjs',

    /*
    |--------------------------------------------------------------------------
    | ChartJS Configuration
    |--------------------------------------------------------------------------
    |
    | The chartjs configuration for all the charts generated by this package.
    |
    */

    'chartjs' => [
        'default_color' => '#000000', // default color of the chart elements
        'responsive' => true, // responsive chart
        'maintainAspectRatio' => false, // maintain aspect ratio
        'options' => [
            'scales' => [
                'x' => [
                    'beginAtZero' => true, // Start X-axis from zero
                ],
                'y' => [
                    'beginAtZero' => true, // Start Y-axis from zero
                ],
            ],
            'legend' => [
                'position' => 'top', // position of the legend
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Chart Settings
    |--------------------------------------------------------------------------
    |
    | Here you can specify settings for each chart. By default, we set the chart
    | to use the Chart.js library, but you can customize this depending on your
    | needs.
    |
    */

    'charts' => [
        'default' => [
            'type' => 'pie', // Default chart type
            'height' => 400, // Default chart height
            'width' => 600,  // Default chart width
        ],
    ],

];
